### ISSUE TITLE
Errors updating sensors

### ISSUE THREAD

**Issue by Deldion** [speleolontra/daikin_residential_altherma#114]
Latest version installed. 
At random times, the following error occurs.
```
This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/daikin_residential_altherma/daikin_api.py:89
Integration: Daikin Residential Controller for Altherma (documentation, issues)
First occurred: 12:46:37 (3 occurrences)
Last logged: 12:48:42

Update for water_heater.altherma fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 198, in async_update
    await self._device.api.async_update()
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 510, in async_update
    self.json_data = await self.getCloudDeviceDetails()
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 466, in getCloudDeviceDetails
    json_puredata = await self.doBearerRequest("/v1/gateway-devices")
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 89, in doBearerRequest
    _LOGGER.debug("BEARER RESPONSE CODE: %s", res.status_code)
UnboundLocalError: local variable 'res' referenced before assignment

```

**Comment by Deldion** [comment]
Also I supose the following is due to poor internet connection.
```
This error originated from a custom integration.

Logger: custom_components.daikin_residential_altherma.daikin_api
Source: custom_components/daikin_residential_altherma/daikin_api.py:510
Integration: Daikin Residential Controller for Altherma (documentation, issues)
First occurred: 12:46:37 (3 occurrences)
Last logged: 12:48:42

REQUEST FAILED: HTTPSConnectionPool(host='api.prod.unicloud.edc.dknadmin.be', port=443): Max retries exceeded with url: /v1/gateway-devices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f611d8550>: Failed to establish a new connection: [Errno 101] Network unreachable'))
REQUEST FAILED: HTTPSConnectionPool(host='api.prod.unicloud.edc.dknadmin.be', port=443): Max retries exceeded with url: /v1/gateway-devices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f605d2c80>: Failed to establish a new connection: [Errno -3] Try again'))
REQUEST FAILED: HTTPSConnectionPool(host='api.prod.unicloud.edc.dknadmin.be', port=443): Max retries exceeded with url: /v1/gateway-devices (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f61ad5b10>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by Deldion** [comment]
Proposing the following in daikin_api.py.
Line 85 to line 105.
```
        try:
            res = await self.hass.async_add_executor_job(func)
        except Exception as e:
            _LOGGER.error("REQUEST FAILED: %s", e)
        else:
            _LOGGER.debug("BEARER RESPONSE CODE: %s", res.status_code)

            if res.status_code == 200:
                try:
                    return res.json()
                except Exception:
                    return res.text
            elif res.status_code == 204:
                return True
                
            if not refreshed and res.status_code == 401:
                _LOGGER.debug("TOKEN EXPIRED: will refresh it (%s)", res.status_code)
                await self.refreshAccessToken()
                return await self.doBearerRequest(resourceUrl, options, True)

            raise Exception("Communication failed! Status: " + str(res.status_code))
```

**Comment by Deldion** [comment]
Obviously, I am very new to how to code for HA.
So I do have some questions.
Will `func = functools.partial(requests.get, resourceUrl, headers=headers)` raise all the regular exceptions `requests` would?
If so, the proper handling would be useful and nice to have.

**Comment by jwillemsen** [comment]
See https://github.com/rospogrigio/daikin_residential/blob/master/custom_components/daikin_residential/daikin_api.py for where this file originally came from. When you have a fix that works for you, please open a pull request.

**Comment by jwillemsen** [comment]
Can you check whether https://github.com/speleolontra/daikin_residential_altherma/pull/116 fixes this for you?
