### ISSUE TITLE
[Issue]: `climate.altherma` (again) missing after update 

### ISSUE THREAD

**Issue by heikone** [speleolontra/daikin_residential_altherma#144]
Dear all,
since the updating to the latest HA version and also keeping up to the latest Daikin Residential Controller for HACS, the climate device for my Heatpump Daikin Altherma 3 R W is again missing. I've notices some other issues reporting this, but the solutions could not provide help to me. Therefore, I've created this new issue and I'm asking for help.

It seems, that only the climate entity is missing. All other are still available (the shown control element "Altherma" is the hot water tank, which is still available):
<img width="332" alt="Bildschirmfoto 2023-04-09 um 10 21 00" src="https://user-images.githubusercontent.com/42500448/230762363-76ca13a9-d89b-48fe-baf0-badd66a10c02.png">

The diagnostic file is also available:
[config_entry-daikin_residential_altherma.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/11185046/config_entry-daikin_residential_altherma.json.txt)

I would appreciate, if somebody could help.
Greetings, Heiko

**Comment by heikone** [comment]
Maybe, this log from Homeassistant is also helpful:
```
Logger: homeassistant.components.climate
Source: custom_components/daikin_residential_altherma/climate.py:110 
Integration: Klima (documentation, issues) 
First occurred: 10:08:07 (1 occurrences) 
Last logged: 10:08:07

Error while setting up daikin_residential_altherma platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 83, in async_setup_entry
    async_add_entities([DaikinClimate(device)], update_before_add=True)
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 110, in __init__
    _LOGGER.info("Support features %s for controlMode %s", self._supported_features, controlMode)
AttributeError: 'DaikinClimate' object has no attribute '_supported_features'
```

**Comment by heikone** [comment]
Another update, that may help for the solution:
My device was currently (during the update) in holiday mode and maybe the necessary information for the climate entity have not been available. Setting the device to normal operation in Onecta app brings back the the climate entity and everything seems to work properly.
The issue seems to be a problem with the holiday mode of the heat pump.
 
The file attached to my first post [https://github.com/speleolontra/daikin_residential_altherma/issues/144#issue-1659795666](url) is a diagnostic file with holiday mode active.

Regards
Heiko

**Comment by jwillemsen** [comment]
Can you retest with the following change made locally: https://github.com/jwillemsen/daikin_residential_altherma/commit/0717166ffc900f04a5bb95819851020fd8660292?

See also https://github.com/speleolontra/daikin_residential_altherma/pull/145

**Comment by heikone** [comment]
Will give it a try and report.
Changes made at my local installation, but it takes some time to make climate.altherma be unavailable when holiday mode is set.
Feedback will follow!

**Comment by jwillemsen** [comment]
New v2.7.0 release is available, see https://github.com/speleolontra/daikin_residential_altherma/releases/tag/v2.7.0
