### ISSUE TITLE
[Issue]:  Add support for ecoMode

### ISSUE THREAD

**Issue by mihsu81** [speleolontra/daikin_residential_altherma#160]
Hello @jwillemsen,

Please add support for "domesticHotWaterTank" and ecoMode as discussed previously in https://github.com/BigFoot2020/daikin_residential_brp069a62/issues/4.

Thank you in advance.

I'm attaching the device logs and HA logs.
[config_entry-daikin_residential_altherma-3b7bdcdcb12794b1accffa573998ccd5.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/12000513/config_entry-daikin_residential_altherma-3b7bdcdcb12794b1accffa573998ccd5.json.txt)
[home-assistant_2023-07-10T09-59-03.352Z.log.txt](https://github.com/speleolontra/daikin_residential_altherma/files/12000577/home-assistant_2023-07-10T09-59-03.352Z.log.txt)

**Comment by jwillemsen** [comment]
That is not a small effort, looks your device has a `managementPointType` with value `domesticHotWaterFlowThrough` instead of `domesticHotWaterTank`. In order to handle that adding that would require https://github.com/speleolontra/daikin_residential_altherma/issues/86 to be implemented. As a hack you could try to change https://github.com/speleolontra/daikin_residential_altherma/blob/f679e2dbb15940d9b4cfa4bf87df8258e21877bb/custom_components/daikin_residential_altherma/const.py#L31C5-L31C5 to `domesticHotWaterFlowThrough`

**Comment by mihsu81** [comment]
Thank you for taking your time to provide the help needed to get it working, at least partially.

After making the sugested change, the sensors get created, but the water_heater entity appears Unavailable and the following errors appear in HA Logs.

![image](https://github.com/speleolontra/daikin_residential_altherma/assets/40715497/7cbb936a-54e9-4911-98b5-4bd5a79679ad)


```
Logger: homeassistant.components.water_heater
Source: custom_components/daikin_residential_altherma/water_heater.py:141
Integration: Water Heater (documentation, issues)
First occurred: 15:13:43 (2 occurrences)
Last logged: 15:13:43

Error adding entities for domain water_heater with platform daikin_residential_altherma
Error while setting up daikin_residential_altherma platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 504, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 788, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1006, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 812, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 214, in state_attributes
    self.current_temperature,
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 141, in current_temperature
    return float(self._device.getValue(ATTR_TANK_TEMPERATURE))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/daikin_residential_altherma/water_heater.py:141
Integration: Daikin Residential Controller for Altherma (documentation, issues)
First occurred: 15:16:59 (1 occurrences)
Last logged: 15:16:59

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1129, in _async_registry_updated
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 742, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 812, in _async_write_ha_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 214, in state_attributes
    self.current_temperature,
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 141, in current_temperature
    return float(self._device.getValue(ATTR_TANK_TEMPERATURE))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: float() argument must be a string or a real number, not 'NoneType'
```

**Comment by jwillemsen** [comment]
Is it correct that you can only set the target temperature for your boiler, can't read the current temperature in the onecta app also? Do you have a screenshot of the onecta app for your boiler?

**Comment by jwillemsen** [comment]
Can you also try this change https://github.com/speleolontra/daikin_residential_altherma/pull/161

**Comment by mihsu81** [comment]
Indeed it doesn't publish the current water temperature to Onecta. You can only set the temperature.
![Screenshot_2023-07-10-19-42-00-57_4bcafe9f204dac669a9d9795053a31bd](https://github.com/speleolontra/daikin_residential_altherma/assets/40715497/6ee671c4-9698-4b63-b1e5-1c6b2164705c)
With https://github.com/speleolontra/daikin_residential_altherma/pull/161 the water_heater entity gets created. It shows Off, Heat Pump and Performance as working modes, but only Off and Heat Pump actually work. Heat Pump is actually the mode "heating".

![Screenshot_2023-07-10-19-50-27-87_c3a231c25ed346e59462e84656a70e50](https://github.com/speleolontra/daikin_residential_altherma/assets/40715497/a5368c56-e9d0-41ee-8b72-90a9a23b9342)

**Comment by jwillemsen** [comment]
For performance probably we need to filter out one value based on your device capabilities, looks a low prio issue, just don’t select it 😉

**Comment by mihsu81** [comment]
> For performance probably we need to filter out one value based on your device capabilities, looks a low prio issue, just don’t select it 😉

Yes absolutely, I was just mentioning the current status. Would it be possible to add the EcoMode switch as well?

**Comment by jwillemsen** [comment]
The `ecoMode` is on the Altherma itself, correct?

```
            "ecoMode": {
              "settable": true,
              "values": [
                "on",
                "off"
              ],
              "value": "on"
            },
```

**Comment by mihsu81** [comment]
> The `ecoMode` is on the Altherma itself, correct?
> 
> ```
>             "ecoMode": {
>               "settable": true,
>               "values": [
>                 "on",
>                 "off"
>               ],
>               "value": "on"
>             },
> ```

Correct.

**Comment by jwillemsen** [comment]
I have a branch with some additional support for holidayMode, maybe it fixes this one also, see https://github.com/speleolontra/daikin_residential_altherma/pull/185

**Comment by jwillemsen** [comment]
https://github.com/speleolontra/daikin_residential_altherma/pull/186 has some in progress work to support your tank type

**Comment by jwillemsen** [comment]
#186 now also checks if the water heater has a powerfulMode before adding that to the list of features supported by the device

**Comment by jwillemsen** [comment]
@mihsu81 Could you test my branch from #186 on your device and let me how that works?

**Comment by mihsu81** [comment]
Unfortunately I get the below errors while using https://github.com/speleolontra/daikin_residential_altherma/pull/186.
The water tank is only used for domestic hot water, and I can only adjust its setpoint without getting the current temperature.

```
Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:507
Integration: Water Heater (documentation, issues)
First occurred: 20:00:05 (1 occurrences)
Last logged: 20:00:05

Error adding entities for domain water_heater with platform daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 214, in capability_attributes
    data[ATTR_OPERATION_LIST] = self.operation_list
                                ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 241, in operation_list
    if hwtd["powerfulMode"]["settable"] == True:
       ~~~~^^^^^^^^^^^^^^^^
KeyError: 'powerfulMode'
```
```
Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:367
Integration: Water Heater (documentation, issues)
First occurred: 20:00:05 (1 occurrences)
Last logged: 20:00:05

Error while setting up daikin_residential_altherma platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 214, in capability_attributes
    data[ATTR_OPERATION_LIST] = self.operation_list
                                ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 241, in operation_list
    if hwtd["powerfulMode"]["settable"] == True:
       ~~~~^^^^^^^^^^^^^^^^
KeyError: 'powerfulMode'
```

**Comment by jwillemsen** [comment]
@mihsu81 Thanks for your test! I made a change that should fix this, can you try again?

**Comment by jwillemsen** [comment]
@mihsu81 Any test results?

**Comment by mihsu81** [comment]
Hi @jwillemsen ,
Appologies for not getting back to you sooner. I was away for the past month.
I've updated the integration to the latest version and pulled the latest changes from PR https://github.com/speleolontra/daikin_residential_altherma/pull/186 and I'm getting the below errors.

```
Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:507
Integration: Water Heater ([documentation](https://www.home-assistant.io/integrations/water_heater), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+water_heater%22))
First occurred: 09:55:33 (1 occurrences)
Last logged: 09:55:33

Error adding entities for domain water_heater with platform daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 225, in state_attributes
    self.current_temperature,
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 138, in current_temperature
    ret =  float(hwtd["sensoryData"]["value"]["tankTemperature"]["value"])
                 ~~~~^^^^^^^^^^^^^^^
KeyError: 'sensoryData'
```
```
Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:367
Integration: Water Heater (documentation, issues)
First occurred: 09:55:33 (1 occurrences)
Last logged: 09:55:33

Error while setting up daikin_residential_altherma platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 225, in state_attributes
    self.current_temperature,
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 138, in current_temperature
    ret =  float(hwtd["sensoryData"]["value"]["tankTemperature"]["value"])
                 ~~~~^^^^^^^^^^^^^^^
KeyError: 'sensoryData'
```

**Comment by jwillemsen** [comment]
Thaks for your test @mihsu81, I made another fix, can you retest with the latest version of my branch?

**Comment by jwillemsen** [comment]
@mihsu81 I committed some other work to this branch by accident, can you switch the branch to another one, see https://github.com/speleolontra/daikin_residential_altherma/pull/196

**Comment by jwillemsen** [comment]
Ok, made another fix, can you retest?

**Comment by jwillemsen** [comment]
@mihsu81 Can you retest, the code was setting the powerful mode to the water heater, but your device doesn't support that mode

**Comment by mihsu81** [comment]
Still getting the same 404 message and the below error:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:29:34 (4 occurrences)
Last logged: 12:30:59

[140270277591232] Communication failed! Status: 404
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 260, in async_set_operation_mode
    await self.async_set_tank_state(operation_mode)
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 206, in async_set_tank_state
    result &= await self._device.set_path(self._device.getId(), self.managementpoint_type, "onOffMode", "", "off")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/device.py", line 441, in set_path
    res = await self.api.doBearerRequest(setPath, setOptions)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 121, in doBearerRequest
    raise Exception("Communication failed! Status: " + str(res.status_code))
Exception: Communication failed! Status: 404
```

**Comment by jwillemsen** [comment]
Found something, one moment

**Comment by mihsu81** [comment]
Attaching just in case .
[error_log-4.txt](https://github.com/speleolontra/daikin_residential_altherma/files/13487284/error_log-4.txt)

**Comment by jwillemsen** [comment]
I think I found it, can you retest?

**Comment by mihsu81** [comment]
Seems to work fine now. Just that it's quite slow to update. I assume this is related to Daikin's recent polling restrictions.

**Comment by jwillemsen** [comment]
Great! This is a first step in refactoring the current support. Less preprocessing when receiving the data from Daikin, at the end the logic to handle all Altherma variants will be easier

**Comment by mihsu81** [comment]
Thanks a lot for your help. There is something to note with the current approach of setting the temperature of the climate entity.
It is causing a fault in the attributes of the climate entity: TargetTemperatureOverruledState becomes true.
Would it be possible to check the currently set mode and use the same?
Thank you.
![Screenshot_2023-11-28-19-43-34-82_c3a231c25ed346e59462e84656a70e50](https://github.com/speleolontra/daikin_residential_altherma/assets/40715497/c7ce35dd-b78a-48f2-972b-cba3b9181c7b)

**Comment by jwillemsen** [comment]
Please open a new issue for other problems else things get lost

**Comment by mihsu81** [comment]
I will continue here because I forgot to mention this during the initial implementation.
When I set the target temperature using the climate entity, the Heating unit sees the action as an override instead of a regular change.
I think this is caused by the fact that currently, the integration only uses _heatingDay_ as _working mode_ instead of reading the current working mode of the heating unit.

The screenshot is from a different integration which displays any fault present in the unit.

![image](https://github.com/speleolontra/daikin_residential_altherma/assets/40715497/52cc7ed6-517e-4113-8e25-c8e4f458fca8)

**Comment by jwillemsen** [comment]
Can you retest https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.1 and when something doesn't work open a new issue in my forked repo?

**Comment by mihsu81** [comment]
Thanks a lot @jwillemsen.
