### ISSUE TITLE
Not loading integration

### ISSUE THREAD

**Issue by Gijsbouhuis** [speleolontra/daikin_residential_altherma#171]
Hi,

I'm having issued loading the integration. I'm having the following error:

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.loader
Source: custom_components/daikin_residential_altherma/daikin_api.py:12
Integration: Daikin Residential Controller for Altherma (documentation, issues)
First occurred: 29 september 2023 om 09:30:05 (2 occurrences)
Last logged: 12:41:48

Unexpected exception importing component custom_components.daikin_residential_altherma
Unexpected exception importing platform custom_components.daikin_residential_altherma.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/daikin_residential_altherma/__init__.py", line 13, in <module>
    from .daikin_api import DaikinApi
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 12, in <module>
    from oic.oic import Client
  File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 20, in <module>
    from jwkest import jwe
  File "/usr/local/lib/python3.11/site-packages/jwkest/jwe.py", line 16, in <module>
    from Cryptodome.Util.number import bytes_to_long
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
ValueError: bad marshal data (unknown type code)
```

**And the following error:**

```
Logger: homeassistant.setup
Source: loader.py:826
First occurred: 29 september 2023 om 09:30:05 (1 occurrences)
Last logged: 29 september 2023 om 09:30:05

Setup failed for custom integration daikin_residential_altherma: Unable to import component: Exception importing custom_components.daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/daikin_residential_altherma/__init__.py", line 13, in <module>
    from .daikin_api import DaikinApi
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 12, in <module>
    from oic.oic import Client
  File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 20, in <module>
    from jwkest import jwe
  File "/usr/local/lib/python3.11/site-packages/jwkest/jwe.py", line 16, in <module>
    from Cryptodome.Util.number import bytes_to_long
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
ValueError: bad marshal data (unknown type code)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 826, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.daikin_residential_altherma
```

Any help is appreciated!

**Comment by jwillemsen** [comment]
Have you tried to restart HA? Check if all files of this custom integration are in the mentioned directory, there should be a daikin_api.py

**Comment by Gijsbouhuis** [comment]
Restarting HA did not solve the issue. All files are available. I haven't tried deleting and reinstalling the integration yet. The daikin app on my phone was showing a pop-up lately about some kind of firmware update for the wifi adapters for the daikin heatpump. I will try reinstalling the integration this afternoon, I'll keep you updated.

**Comment by Gijsbouhuis** [comment]
Reinstalling did not work either. When i tried to reconfigure after reinstallie, i'm getting the following error:

Config-flow kon niet geladen worden: {"message":"Invalid handler specified"}

**Comment by jwillemsen** [comment]
I haven't seen this error, maybe caused by the combination of two integrations?

**Comment by jwillemsen** [comment]
Maybe https://community.home-assistant.io/t/fatal-python-error-initsite/159957/5 helps, could be an installation issue

**Comment by Gijsbouhuis** [comment]
Hello Johnny, I decided to restore a backup which solved the problem. Many thanks for your help and thank you for the great integration!
