### ISSUE TITLE
2024.1 issues

### ISSUE THREAD

**Issue by neildsb** [speleolontra/daikin_residential_altherma#213]
I have a few logs errors with 2014.1 - no Hot Water Values appears to the be main issue

Core
2024.1.0
Supervisor
2023.12.0
Operating System
11.2
Frontend
20240103.3

```
Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:368
Integration: Water Heater (documentation, issues)
First occurred: 10:00:41 pm (1 occurrences)
Last logged: 10:00:41 pm

Error while setting up daikin_residential_altherma platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 244, in capability_attributes
    if WaterHeaterEntityFeature.OPERATION_MODE in self.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable



Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1520
First occurred: 10:00:42 pm (1 occurrences)
Last logged: 10:00:42 pm

Entity None (<class 'custom_components.daikin_residential_altherma.climate.DaikinClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE: 1>, please create a bug report at https://github.com/speleolontra/daikin_residential_altherma/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Logger: homeassistant.config_entries
Source: config_entries.py:561
First occurred: 9:53:24 pm (1 occurrences)
Last logged: 9:53:24 pm

Error unloading entry Daikin for daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/__init__.py", line 100, in async_unload_entry
    await asyncio.wait(
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 425, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.


Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:204
Integration: Sensor (documentation, issues)
First occurred: 10:00:40 pm (8 occurrences)
Last logged: 10:00:42 pm

STATE_CLASS_MEASUREMENT was used from daikin_residential_altherma, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/speleolontra/daikin_residential_altherma/issues
STATE_CLASS_TOTAL_INCREASING was used from daikin_residential_altherma, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please create a bug report at https://github.com/speleolontra/daikin_residential_altherma/issues
```

**Comment by pwwukpw** [comment]
Same issue here.

**Comment by jwillemsen** [comment]
Fixed as part of https://github.com/jwillemsen/daikin_residential_altherma

**Comment by neildsb** [comment]
thanks @jwillemsen just waiting for HACS to pull the update

**Comment by jwillemsen** [comment]
My version of the integration is not yet available on HACS, waiting on https://github.com/hacs/default/pull/2234

**Comment by pwwukpw** [comment]
Thanks for the rapid fix .. much appreciated, use to heat hot water with excess solar and low dynamic priced electricity,  many.  Could you message here when on HACS.

**Comment by jwillemsen** [comment]
Fixed by https://github.com/home-assistant/core/pull/107091
