### ISSUE TITLE
After updating HomeAssistant Intergration does not load 

### ISSUE THREAD

**Issue by mbouwm** [speleolontra/daikin_residential_altherma#215]
daikin_residential_altherma does not load after updating homeassistant.
After updating daikin_residential_altherma it is still not working.

What can I do to make this work again?

Regards,
Martien

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 15:37:42 (1 occurrences)
Last logged: 15:37:42

Setup failed for custom integration 'daikin_residential_altherma': Unable to import component: cannot import name 'SensorDeviceClass' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/daikin_residential_altherma/__init__.py", line 11, in <module>
    from .const import DOMAIN, DAIKIN_API, DAIKIN_DEVICES, CONF_TOKENSET
  File "/config/custom_components/daikin_residential_altherma/const.py", line 3, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'SensorDeviceClass' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by jwillemsen** [comment]
We lack details of what you exactly have installed, HomeAssistant 2024.1.0 is broken for the water heater, you need 2024.1.1. You can also try https://github.com/jwillemsen/daikin_residential_altherma, that works for me without problems

**Comment by mbouwm** [comment]
Hi,
It is working again. For some kind of reason I updated to an old version of daiking_residental_altherma.
Currently the manifest shows version 3.3.1 

When using this new version it is working again.
:-)
