### ISSUE TITLE
[Issue]: Unable to import component: cannot import name 'SensorDeviceClass' from 'homeassistant.const'

### ISSUE THREAD

**Issue by mfr00t** [speleolontra/daikin_residential_altherma#227]
I always had installed this daikin_residential_altherma extension by cloning the master, and copying over the custom_component contents (HA running as podman container), but haven't updated the extension for a while. Today i pulled again, and the extension isn't loading anymore, due to the following error message:

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 13:16:58 (1 occurrences)
Last logged: 13:16:58

```
Setup failed for custom integration 'daikin_residential_altherma': Unable to import component: cannot import name 'SensorDeviceClass' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/daikin_residential_altherma/__init__.py", line 11, in <module>
    from .const import DOMAIN, DAIKIN_API, DAIKIN_DEVICES, CONF_TOKENSET
  File "/config/custom_components/daikin_residential_altherma/const.py", line 3, in <module>
    from homeassistant.const import (
ImportError: cannot import name 'SensorDeviceClass' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```

Image version:
```
$ podman images homeassistant/home-assistant:latest 
REPOSITORY                              TAG         IMAGE ID      CREATED     SIZE
docker.io/homeassistant/home-assistant  latest      a8e0abc37a65  2 days ago  1.95 GB
```

Tried with older HA images aswell (not working, for sure)
Switched to tagged v2.8.2 zip-archive - now it's loading again.
How may i get the master back to work, as i like the bleeding edge integration :D

**Comment by mfr00t** [comment]
Thank you very much @jwillemsen :)
