### ISSUE TITLE
Only few entities shown for Altherma 3 and BRP069A78

### ISSUE THREAD

**Issue by jwillemsen** [speleolontra/daikin_residential_altherma#5]
Trying to get our Altherma 3 heat pump with BRP069A78 wifi module connected to home assistant. This integration does show the alterma 3 within home-assistant but it only shows whether boost is enabled, the acs state and once 30C.

In addition to the alterma 3 we do have 4 wifi units, they are all visible within the Daikin Residential Controller, could this be a problem?

[daikin_data.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/7924858/daikin_data.json.txt)

**Comment by jwillemsen** [comment]
Enabled warning logging in HA, now I get this in the log

```
2022-01-24 12:23:15 WARNING (MainThread) [custom_components.daikin_residential_altherma] Get devices: 
2022-01-24 12:23:16 ERROR (MainThread) [homeassistant.components.climate] Error while setting up daikin_residential platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/daikin_residential/climate.py", line 85, in async_setup_entry
    async_add_entities([DaikinClimate(device)], update_before_add=True)
  File "/config/custom_components/daikin_residential/climate.py", line 99, in __init__
    ATTR_SWING_MODE: self._device.swing_modes,
  File "/config/custom_components/daikin_residential/daikin_base.py", line 239, in swing_modes
    hMode = self.getData(ATTR_HSWING_MODE)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 106, in getData
    cmd_set = self.getCommandSet(param)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 101, in getCommandSet
    cmd_set[2] = cmd_set[2].replace("%operationMode%", operation_mode)
TypeError: replace() argument 2 must be str, not None
2022-01-24 12:23:16 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up daikin_residential_altherma platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/daikin_residential_altherma/sensor.py", line 48, in async_setup_entry
    print("DAMIANO append sensor = {}".format(sensor))
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 888, in __repr__
    return f"<Entity {self.name}: {self.state}>"
  File "/config/custom_components/daikin_residential_altherma/sensor.py", line 160, in state
    return self._device.leavingWaterTemperature
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 357, in leavingWaterTemperature
    t = float(self.getValue(ATTR_INSIDE_TEMPERATURE))
TypeError: float() argument must be a string or a number, not 'NoneType'
2022-01-24 12:23:16 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 217, in hvac_modes
    return self._device.hvac_modes
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 193, in hvac_modes
    for mode in self.getValidValues(ATTR_OPERATION_MODE):
TypeError: 'NoneType' object is not iterable
2022-01-24 12:23:16 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 217, in hvac_modes
    return self._device.hvac_modes
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 193, in hvac_modes
    for mode in self.getValidValues(ATTR_OPERATION_MODE):
TypeError: 'NoneType' object is not iterable
2022-01-24 12:23:16 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 217, in hvac_modes
    return self._device.hvac_modes
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 193, in hvac_modes
    for mode in self.getValidValues(ATTR_OPERATION_MODE):
TypeError: 'NoneType' object is not iterable
2022-01-24 12:23:16 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 217, in hvac_modes
    return self._device.hvac_modes
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 193, in hvac_modes
    for mode in self.getValidValues(ATTR_OPERATION_MODE):
TypeError: 'NoneType' object is not iterable
2022-01-24 12:23:16 ERROR (MainThread) [homeassistant.components.climate] Error while setting up daikin_residential_altherma platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 226, in capability_attributes
    ATTR_HVAC_MODES: self.hvac_modes,
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 217, in hvac_modes
    return self._device.hvac_modes
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 193, in hvac_modes
    for mode in self.getValidValues(ATTR_OPERATION_MODE):
TypeError: 'NoneType' object is not iterable
```

**Comment by jwillemsen** [comment]
Is maybe the problem that ATTR_OPERATION_MODE is "operation_mode" but in my json file it looks to be operationMode, see line 717 of the json file

**Comment by jwillemsen** [comment]
Maybe caused by the fact that I have multiple daikin models, shouldn't there be a filter to only handle "deviceModel": "Altherma"

**Comment by speleolontra** [comment]
There's the difference in json with mine (at right):
![immagine](https://user-images.githubusercontent.com/10747617/150875744-cab4e645-f141-49d8-8370-31f6c5244c2e.png)

![immagine](https://user-images.githubusercontent.com/10747617/150875826-6fd5c5b6-15fd-437c-9eb1-0bc0a9e37e12.png)
(maybe null Name cause errors?)

![immagine](https://user-images.githubusercontent.com/10747617/150876082-7c8b2127-609d-4191-af9a-ae8ec6414d48.png)

![immagine](https://user-images.githubusercontent.com/10747617/150876223-f72ea479-f362-4b04-a229-12dac2b94c6d.png)

![immagine](https://user-images.githubusercontent.com/10747617/150876398-a268c9cb-ccf7-4cfa-80b3-90d055f97cc1.png)

![immagine](https://user-images.githubusercontent.com/10747617/150876601-ce960232-403e-4609-84a7-a65e8cdec60d.png)

![immagine](https://user-images.githubusercontent.com/10747617/150876719-fb19c71c-76f2-4b7c-b34f-b1b1e34e37da.png)
(maybe null Name cause errors?)

Can you verify if firmware is updated?
![immagine](https://user-images.githubusercontent.com/10747617/150877273-523832ca-92a8-4952-89b9-be85c3f354e5.png)

I hope this was useful...
Lontra

**Comment by jwillemsen** [comment]
I have a madoka thermostat attached (see #2), very likely that is the reason I have some roomTemperature values.

When we installed the wifi module the unit did upgrade the firmware, but seems 6.3.0 is the latest I got, unit got installed October 2021. 

The strings you have in name where I have an empty string, do you see them in the home assistant UI back?

**Comment by jwillemsen** [comment]
Could you attach your json here, than I can compare the content and try a few things, when I check the latest json on my system I do see a name value now. You have a different key, looks none of the real data is parsed correctly

Do you only have one alterma attached, or also other daikin units like me? Could that maybe cause an issue?

**Comment by speleolontra** [comment]
>The strings you have in name where I have an empty string, do you see them in the home assistant UI back?
Yes, I see them in home assistant but set up in Daikin app.

>Do you only have one alterma attached, or also other daikin units like me? Could that maybe cause an issue?
Altherma only. Maybe other units cause issues, i can't try...

This is my json: I hope is usefule for you.
[daikin_puredata - Copy.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/7937577/daikin_puredata.-.Copy.json.txt)

Lontra
