### ISSUE TITLE
WaterTank Heater unable set temeperature

### ISSUE THREAD

**Issue by palecs** [speleolontra/daikin_residential_altherma#96]
Hello Im trying all new features and I found this issue. 

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/daikin_residential_altherma/water_heater.py:167
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:36:41 (1 occurrences)
Last logged: 18:36:41

[2600421960] 'DaikinWaterTank' object has no attribute 'getValue'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 370, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 193, in async_set_temperature
    await self.async_set_tank_temperature(kwargs[ATTR_TEMPERATURE])
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 167, in async_set_tank_temperature
    if self.getValue(ATTR_TANK_ON_OFF) != ATTR_STATE_ON:
AttributeError: 'DaikinWaterTank' object has no attribute 'getValue'
```
Diag data attached.
[config_entry-daikin_residential_altherma-b85e79ba916040a955d14a8a6557adc8.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/10816560/config_entry-daikin_residential_altherma-b85e79ba916040a955d14a8a6557adc8.json.txt)

Thank you but making a lot of tests :D. Thank you really for fast responses.

**Comment by jwillemsen** [comment]
Should be fixed, https://github.com/speleolontra/daikin_residential_altherma/pull/97

**Comment by palecs** [comment]
Confirming Im now able to set temperature, if altherma is not using fixed plan for heating and can be moved now to homeassistent. Thank you.
